### ISSUE TITLE
Webpack Build: TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by ViniciusResende** [stylus/stylus#2640]
**To reproduce:**

```js
{
  test: /\.styl$/,
  include: [path.resolve(__dirname, '../some/path/style.styl')],
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1,
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          plugins: [cssNano()],
        },
      },
    },
    {
      loader: 'stylus-loader',
    },
  ],
},
```

**Current behavior:**

With this configuration in my webpack config for handling .styl files, when I try to build my app I receive the following error:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'nodeName' of undefined`, that comes from `node_modules/stylus/lib/visitor/deps-resolver.js:41:16`

**Expected behavior:**

I expected that I would have no problems while building my app since it was correctly working with the 3.0.2 stylus-loader version.

**Environment information:**

- `stylus` version: 0.55.0
- `nodejs` version: 14.17.6
- `stylus-loader` version: 6.2.0
- `mini-css-extract-plugin` version: 2.4.5
- `css-loader` version: 6.5.1
- `postcss-loader` version: 6.2.0
- `cssnano` version: 5.0.11

If necessary, I could provide more info about my webpack config

**Comment by iChenLei** [comment]
@ViniciusResende  Can your provide a minial reproducation code repo? Thanks

**Comment by ViniciusResende** [comment]
@iChenLei I actually did a new repository but when I changed some specific configs of my repository, that had shown 
 the problem, it turned to work, which probably means that something locally configured is directly influencing the `stylus-loader` to work properly. Sorry for wasting your time, I'm going to investigate my own repository.

**Comment by iChenLei** [comment]
Thank you  @ViniciusResende

**Comment by ViniciusResende** [comment]
I have solved my problem, but for purposes of documentation, I will write here what was generating the problem, in that way someone that can possibly have the same issue as I had can solve it more quickly.

@iChenLei I tried to reproduce the error in another repository, but couldn't find a way to do so easily. Although, I find out that the compilation error would be related to something in my code, most probably in a `.styl` file.

After doing a more stressful investigation, I could find two files that were creating the problem. Actually, I had some code that appears to be supported in `stylus-loader: 3.0.2` but not in `stylus-loader: 6.2.0`. 

Here's an example:

```stylus
.myclass {
  margin-top: 2px;
  z-index: 12;
  @include box-shadow($color-dark-2 2px 2px 10px);  transition: 0.2s linear all;
  top: 53px;
}
```

To fix the issue I had to remove the `@include` line and do some workaround to maintain the expected result.

I'm not sure if it's the expected result after updating to the newest version of `stylus-loader`, I couldn't find some migration guide telling about this deprecation. Although, if it's the expected behavior, I think is valid to cast some URL to documentation about it and close the issue @iChenLei.

**Comment by iChenLei** [comment]
Wow, thanks for the great deep investigation !  Is `box-shadow` a simple normal stylus function ? Can you provide the raw code of `box-shadow()`? So I can reproduce it to solve the real origin issue.

**Comment by ViniciusResende** [comment]
Actually, I've changed the name of the stylus function to `box-shadow` to enunciate it on the conversation, it's actually called `shadow-box`, and this is the code of the function:

```stylus
shadow-box(color = rgba(0, 0, 0, 0.1)) {
  -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
  -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
  box-shadow: 0 1px 2px color;
}
```

Wish it helps.
