### ISSUE TITLE
attribute selector broken in 0.39.1

### ISSUE THREAD

**Issue by awick** [stylus/stylus#1174]
Works in 0.38

```
[contenteditable]
  outline: 1px dotted #aaa
  min-height: 20px
```

in 0.39.1 I now get an error

```
ERROR -  [TypeError: undefined:4
   1| [contenteditable]
   2|   outline: 1px dotted #aaa
   3|   min-height: 20px
 > 4|

undefined is not a function
]
```
